version: '3.1'

services:

    db_postgres:
        image: postgres
        volumes:
            - "/home/${USER}/www/volume-postgresql:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD: root

    db_mysql:
        image: mysql
        volumes:
            - "/home/${USER}/www/volume-mysql:/var/lib/mysql"
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root

    adminer:
        image: adminer
        ports:
            - 8080:8080

    php7.0:
        build: ./php7.0
        volumes:
            - "/home/${USER}/www/apache:/var/www/html"
        ports:
            - 80:80

    ruby2.4:
        build: ./ruby2.4
        